# Generated by Django 3.0.2 on 2020-02-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_manager_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
